<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Kimai_Auth_Abstract' => $vendorDir . '/Kimai/Auth/Abstract.php',
    'Kimai_Auth_Http' => $vendorDir . '/Kimai/Auth/Http.php',
    'Kimai_Auth_Kimai' => $vendorDir . '/Kimai/Auth/Kimai.php',
    'Kimai_Auth_Ldap' => $vendorDir . '/Kimai/Auth/Ldap.php',
    'Kimai_Auth_Ldapadvanced' => $vendorDir . '/Kimai/Auth/Ldapadvanced.php',
    'Kimai_Database_Abstract' => $vendorDir . '/Kimai/Database/Abstract.php',
    'Kimai_Database_Mysql' => $vendorDir . '/Kimai/Database/Mysql.php',
    'Kimai_Extensions' => $vendorDir . '/Kimai/Extensions.php',
    'Kimai_Format' => $vendorDir . '/Kimai/Format.php',
    'Kimai_Invoice_AbstractRenderer' => $vendorDir . '/Kimai/Invoice/AbstractRenderer.php',
    'Kimai_Invoice_HtmlRenderer' => $vendorDir . '/Kimai/Invoice/HtmlRenderer.php',
    'Kimai_Invoice_HtmlToPdfRenderer' => $vendorDir . '/Kimai/Invoice/HtmlToPdfRenderer.php',
    'Kimai_Invoice_OdtRenderer' => $vendorDir . '/Kimai/Invoice/OdtRenderer.php',
    'Kimai_Invoice_PrintModel' => $vendorDir . '/Kimai/Invoice/PrintModel.php',
    'Kimai_Logger' => $vendorDir . '/Kimai/Logger.php',
    'Kimai_Registry' => $vendorDir . '/Kimai/Registry.php',
    'Kimai_Remote_Api' => $vendorDir . '/Kimai/Remote/Api.php',
    'Kimai_Remote_Database' => $vendorDir . '/Kimai/Remote/Database.php',
    'Kimai_Rounding' => $vendorDir . '/Kimai/Rounding.php',
    'Kimai_Translations' => $vendorDir . '/Kimai/Translations.php',
    'Kimai_Update_Check' => $vendorDir . '/Kimai/Update/Check.php',
    'Kimai_Update_Version' => $vendorDir . '/Kimai/Update/Version.php',
    'Kimai_User' => $vendorDir . '/Kimai/User.php',
    'Kimai_View' => $vendorDir . '/Kimai/View.php',
    'PclZip' => $vendorDir . '/TinyButStrong/pclzip.lib.php',
    'clsTbsDataSource' => $vendorDir . '/TinyButStrong/tinyButStrong.class.php',
    'clsTbsLocator' => $vendorDir . '/TinyButStrong/tinyButStrong.class.php',
    'clsTinyButStrong' => $vendorDir . '/TinyButStrong/tinyButStrong.class.php',
    'tinyDoc' => $vendorDir . '/TinyButStrong/tinyDoc.class.php',
    'tinyDocException' => $vendorDir . '/TinyButStrong/tinyDoc.class.php',
);
