<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Zend_' => array($vendorDir . '/zendframework/zendframework1/library'),
    'PHPExcel' => array($vendorDir . '/phpoffice/phpexcel/Classes'),
    'Kimai_' => array($vendorDir),
);
