<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    '77a96519c4483cee8899338015bc0df2' => $vendorDir . '/phpclasses/ultimatemysql/mysql.class.php',
);
