<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'PclZip' => $vendorDir . '/TinyButStrong/pclzip.lib.php',
    'clsTbsDataSource' => $vendorDir . '/TinyButStrong/tinyButStrong.class.php',
    'clsTbsLocator' => $vendorDir . '/TinyButStrong/tinyButStrong.class.php',
    'clsTinyButStrong' => $vendorDir . '/TinyButStrong/tinyButStrong.class.php',
    'tinyDoc' => $vendorDir . '/TinyButStrong/tinyDoc.class.php',
    'tinyDocException' => $vendorDir . '/TinyButStrong/tinyDoc.class.php',
);
