<?php
/**
 * This file is part of 
 * Kimai - Open Source Time Tracking // http://www.kimai.org
 * (c) 2006-2009 Kimai-Development-Team
 * 
 * Kimai is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; Version 3, 29 June 2007
 * 
 * Kimai is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with Kimai; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 * 
 */

// This file was automatically generated by the installer

$server_hostname = "localhost"; 
$server_database = "0711test";
$server_username = "root";     
$server_password = "root";
$server_conn     = "pdo";   
$server_type     = "mysql";        
$server_prefix   = "kimai_";   
$language        = "de";

if (!defined('WEBROOT')) {
    define('WEBROOT', dirname(dirname(__FILE__)) . DIRECTORY_SEPARATOR);
}

?>